class Buttons:
    # Navigation
    enter_birth_data = "Ввести данные рождения"
    back = "🔙 Назад"
    main_menu = "В главное меню"
    back_to_menu = "Вернуться в меню"
    back_to_adminpanel = "Назад в админ-панель"
    decline = "Нет вернуться назад ❎"
    confirm = "Подтверждаю ☑"
    # Time of day
    night = "Ночь"
    morning = "Утро"
    day = "День"
    evening = "Вечер"
    # Predictions
    prediction = "🔮Прогноз"
    prediction_no_access = "🔓Прогноз"
    prediction_for_date = "🕓 Прогноз на дату"
    prediction_for_today = "Прогноз на сегодня"
    daily_prediction = "⌚️ Ежедневный прогноз"
    day_selection = "✅ Подбор дня"
    check_another_date = "Проверить другую дату"
    # Subscription
    subscription = "🌟Подписка"
    buy_subscription = "💳 Купить подписку"
    renew_subscription = "👍 Продлить подписку"
    one_month = "1 месяц | 590 рублей"
    two_month = "2 месяца | 1100 рублей"
    three_month = "3 месяца | 1550 рублей"
    six_month = "6 месяцев | 2900 рублей"
    twelve_month = "12 месяцев | 5400 рублей"
    yookassa = "YooKassa"
    prodamus = "Prodamus"
    offer = "Оффер"
    redirect_button_text = "Оплатить подписку"
    check_payment_status = "Проверить статус платежа"
    use_this_promocode = "Использовать этот промокод"
    enter_promocode = "Ввести промокод"
    activate_promocode = "Активировать промокод"
    try_in_deal = "Испытать в деле"
    # Profile settings
    profile_settings = "⚙️Настройки профиля"
    change_timezone = "✈️Смена часового пояса"
    name = "✍️ Имя"
    theme = "🌃 Тема"
    gender = "👤 Пол"
    male = "🙋‍♂️Мужчина"
    female = "🙋‍♀️Женщина"
    # Card of day
    card_of_day = "🃏Карта Дня"
    # Moon in sign
    moon_in_sign = "🌗 Луна в знаке"
    favorable = "🟢 Благоприятно"
    unfavorable = "🔴 Неблагоприятно"
    blank_moon = "🌒 Холостая луна"
    general = "Общий"
    # General predictions
    general_predictions = "🌒 Общие прогнозы"
    prediction_on_day = "🗓️ Общий прогноз на день"
    prediction_on_week = "📆 Общий прогноз на неделю"
    prediction_on_month = "📅 Общий прогноз на месяц"
    # Admin
    add_card_of_day = "Добавить карту дня"
    user_settings = "Настройки пользователя"
    delete_user_subscription = "Выключить подписку пользователя"
    general_predictions_add = "Добавление Общих Прогнозов"
    change_user_subscription_end = "Изменить дату окончания подписки"
    change_user_birth_datetime = "Изменить дату рождения"
    statistics = "Статистика"
    broadcast = "Рассылка"
    # Misc
    dreams = "💫 Сны"
    about_bot = "🤔 О боте"
    support = "📞 Поддержка"
    try_again = "Попробовать ещё раз"
    compatibility = "💞Совместимость"
    choose_another_action = "👉 Выбрать другое событие"

bt = Buttons()
